### ISSUE TITLE
Flask-RESTX

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATservice#15]
I was wondering whether there are any plans of changing the framework to Flask-RESTX, which provides some benefits for development and contains Swagger-UI. Our team can help implementing it.

https://flask-restx.readthedocs.io/en/latest/

**Comment by w-is-h** [comment]
Hi @sandertan, do not have anything against changing the framework - we should look into existing options and find the best. Maybe Flask-RESTX or [FastAPI](https://github.com/tiangolo/fastapi) or something else.

**Comment by sandertan** [comment]
👍 will close this for now, can pick it up in future.
