### ISSUE TITLE
spaCy model configuration

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATservice#19]
Hi thanks for updating this repo to use the latest MedCAT. We've been able to use it with Dutch MedCAT & spaCy models in our fork.

I was wondering whether you are open to changing how spaCy models are handled. Currently:
- The English models are defined in the Dockerfile.
- The MedCAT processor retrieves the spaCy model from an environment variable.
- The CDB includes a config with a spaCy model parameter, but this is not used because of:

https://github.com/CogStack/MedCATservice/blob/026d8acf0d8c13614ec67a1cef144431e60939ec/medcat_service/nlp_processor/medcat_processor.py#L193

It would be nice to use the spaCy model defined in the CDB and download this model if it is not available on the system, and/or make the Dockerfile spaCy models configurable, perhaps with Docker ARG?

Also, since the recent MedCAT releases have the parameters in the CDB, the `envs/env_medcat*` files can be removed right?

**Comment by w-is-h** [comment]
I think long-term the service should switch to model-packs, they internally contain the spacy models so this will not be necessary, let me know what you think.

**Comment by vladd-bit** [comment]
I agree with this, will make sure model packs will be part of the the next release.

**Comment by sandertan** [comment]
With model-pack you mean a bundle of the CDB, Vocab, spaCy model and parameters? That sounds awesome.

**Comment by w-is-h** [comment]
Yes, plus meta annotation models (see [here](https://github.com/CogStack/MedCAT#install-using-pip-requires-python-36))

**Comment by vladd-bit** [comment]
The model pack stuff is now added, check the `env_app` file for the var. At the moment it is possible to add more meta_cats on top of the ones provided in the model pack, not sure if this is ok or not (or if its fully useful).

**Comment by sandertan** [comment]
Nice! I'll check it out in our next deployment.
