### ISSUE TITLE
Entity ID as key in API response

### ISSUE THREAD

**Issue by sandertan** [CogStack/MedCATservice#20]
Hi @vladd-bit , during upgrading MedCATservice I noticed that in the API response `entities` now contains a dictionary instead of list, and it uses entity ID as a key . For example, "0" and "1" in :
> "annotations": {"entities": {**"0"**: {"cui": "C0027361", "id": **0**,.....}, **"1"**: {"cui": "C001111", "id": **1**......}......

The previous implementation of MedCATService we used didn't have this entity ID. In that version, `entities` contained a list of found entities, instead of the current dictionary with a variable number of keys. What's the rational behind this change? The entity ID is already in the entity-dictionary itself, and the new format requires an extra step when quering the data, for example: `nlp.*.cui: C0027361` instead of `nlp.cui: C0027361`.

I guess it's possible to convert this dictionary to a list with Jolt in NiFi if we want, but perhaps it's nicer to output the list at the source.

**Comment by w-is-h** [comment]
To add the rationale behind the change (as it is caused by medcat): in certain cases, you want to access the annotations by ID, before, you would have to loop through a list to find the right ID, while currently, you can access it directly. But, this made sense in MedCAT, for the service not sure what is better, let me know what you think.

**Comment by sandertan** [comment]
For what kind of cases is the entity ID important? As far as I understand it, it's a variable data value, which makes more sense to be a value instead of a key.

If the entity ID does not have a function in the service, I think the previous format is a better fit.

**Comment by w-is-h** [comment]
Went back to find why this was changed, it was useful for meta-annotations in the old approach, currently, this is not needed/useful anymore. 

I agree that it makes more sense if it is a variable, so will be changed. If you have time feel free to submit a PR to the MedCAT repo as the change will be propagated.

**Comment by vladd-bit** [comment]
Since this was in the dev branch for a while, it's now on the master branch, see ANNOTATIONS_ENTITY_OUTPUT_MODE in the env_medcat file (change the setting to list). By default I think the service should respect whatever MedCAT outputs, so the dict ent_id will be used.

**Comment by sandertan** [comment]
Thanks @vladd-bit we'll update our MC service containers with that!
